package rw.dietplanner.dietplanner.utils

object Constants {
    const val API_ROOT = "http://10.250.4.148:8000/api/"
//    const val API_ROOT = "http://192.168.1.125:8000/api/"
    const val API_BASE_ROOT = "http://10.250.4.148:8000/"

    const val STATE_LOADING = "loading"
    const val STATE_IDLE = "idle"
    const val AUTHENTICATION_PREFS = "authentication_prefs"
    const val USER_PREFS = "user_prefs"
    const val ID = "id"
    const val PREFERENCES = "preferences"
    const val USERNAME = "username"
    const val PASSWORD = "password"
    const val TOKEN = "token"
    const val PROFILE = "profile"
    const val FIRST_NAME = "first_name"
    const val LAST_NAME = "last_name"
    const val EMAIL = "email"
    const val INGREDIENTS = "ingredients"
    const val NUTRIENTS = "nutrients"
    const val GROCERIES = "groceries"
    const val MY_RECIPES = "my_recipes"
    const val WELCOME_PAGE_NUMBER = "welcome_page_number"
    const val WELCOME_PAGE_CAPTION = "welcome_page_caption"
    const val WELCOME_PAGE_IMAGE_ID = "welcome_page_image_id"
    const val NAME = "name"
    const val RECIPE = "recipe"
    const val MEAL_PLAN = "meal_plan"
}